name: Build Latest Preview
on:
  push:
    branches:
      - main

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    with:
      build_type: Debug
  test:
    uses: ./.github/workflows/test.yml
  test-jni:
    uses: ./.github/workflows/test-jni.yml
  build:
    needs: [lint, test, test-jni]
    uses: ./.github/workflows/build.yml
    with:
      build_type: Debug

  upload-preview:
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update Tag
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git tag -f latest-preview ${{ github.sha }}
          git push -f origin latest-preview
      - name: Download Artifacts
        uses: actions/download-artifact@v4
      - name: Rename APK Files
        run: |
          mv -f minibrowser-Debug/debug/minibrowser-debug.apk minibrowser-latest.apk
          mv -f mediaplayer-Debug/debug/mediaplayer-debug.apk mediaplayer-latest.apk
          mv -f webdriver-Debug/debug/webdriver-debug.apk webdriver-latest.apk
      - name: Delete Artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: |
            minibrowser-Debug
            mediaplayer-Debug
            webdriver-Debug
      - name: Upload Latest Preview Files
        uses: softprops/action-gh-release@v2
        with:
          name: "Latest Preview"
          tag_name: latest-preview
          prerelease: true
          files: |
            minibrowser-latest.apk
            mediaplayer-latest.apk
            webdriver-latest.apk
