name: JNI Tests
on: workflow_call

jobs:
  check-jni:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Javaâ„¢ Setup
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Check JNI
        run: |
          cd tools/jni-test && \
          cmake -S. -Bbuild && \
          cmake --build build --target run
